"""SQLAlchemy 2.x foundation (frozen module namespace: database).

PostgreSQL 16+ is the single canonical relational database (spec doc 02 §1).
Public IDs are opaque strings (never sequential DB IDs); internal surrogate
keys are allowed only for non-public association/event rows.

Schema changes happen exclusively through Alembic migrations.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager

from sqlalchemy import MetaData, create_engine
from sqlalchemy.engine import Engine, make_url
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from paperintel.config.settings import AppConfig

#: Deterministic constraint names keep autogenerated migrations stable.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all canonical models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def create_engine_from_settings(
    settings: AppConfig,
    *,
    url_override: str | None = None,
    echo: bool | None = None,
) -> Engine:
    """Create an Engine from application settings.

    Raises:
        paperintel.errors.DomainError: DB_001 when the URL is unusable.
    """
    url = url_override or settings.database.url
    try:
        make_url(url)
    except Exception as exc:  # noqa: BLE001 - re-raised as a domain error
        from paperintel.errors import DomainError  # noqa: PLC0415

        raise DomainError(
            "DB_001",
            message="DATABASE_URL is not a valid SQLAlchemy URL.",
            details={"reason": str(exc.__class__.__name__)},
        ) from exc
    return create_engine(
        url,
        echo=settings.database.echo if echo is None else echo,
        pool_size=settings.database.pool_size,
        max_overflow=settings.database.max_overflow,
        pool_pre_ping=True,
    )


def create_session_factory(engine: Engine) -> sessionmaker[Session]:
    return sessionmaker(bind=engine, expire_on_commit=False, autoflush=False)


@contextmanager
def session_scope(factory: sessionmaker[Session]) -> Iterator[Session]:
    """Transactional scope: commit on success, rollback on error.

    Exceptions are never swallowed (spec doc 06 §16): the transaction is
    rolled back and the original exception propagates.
    """
    session = factory()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


__all__ = [
    "Base",
    "NAMING_CONVENTION",
    "create_engine_from_settings",
    "create_session_factory",
    "session_scope",
]
