"""base schema

Revision ID: bde0be4528ea
Revises:
Create Date: 2026-09-17 16:03:45.421222
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bde0be4528ea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector provides canonical vector retrieval (spec doc 02 §1).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.String(length=32), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PDF",
                "FIGURE",
                "TABLE_IMAGE",
                "EVIDENCE_CROP",
                "LLM_OUTPUT",
                "DEBUG",
                name="assetkind",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "retention_class",
            sa.Enum(
                "KEEP",
                "CACHE",
                "TEMP",
                "DEBUG_TTL",
                name="retentionclass",
                native_enum=False,
                length=48,
            ),
            server_default=sa.text("'KEEP'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("asset_id", name=op.f("pk_assets")),
        sa.UniqueConstraint("sha256", name=op.f("uq_assets_sha256")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_assets_storage_key")),
    )
    op.create_table(
        "collections",
        sa.Column("collection_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("research_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("preferred_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("relevance_notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("collection_id", name=op.f("pk_collections")),
    )
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.String(length=32), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "PAPER",
                "PAPER_VERSION",
                "AUTHOR",
                "AFFILIATION",
                "VENUE",
                "METHOD",
                "DATASET",
                "METRIC",
                "TECHNIQUE",
                "TASK",
                "DOMAIN",
                "PROJECT",
                "CODE_REPOSITORY",
                "CLAIM",
                name="entitytype",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_entities")),
        sa.UniqueConstraint("entity_type", "normalized_name", name="uq_entity_type_name"),
    )
    op.create_table(
        "papers",
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.Column("canonical_title", sa.Text(), nullable=False),
        sa.Column("normalized_title", sa.Text(), nullable=False),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("primary_language", sa.String(length=16), nullable=True),
        sa.Column("paper_type", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("paper_id", name=op.f("pk_papers")),
        sa.UniqueConstraint("doi", name=op.f("uq_papers_doi")),
    )
    op.create_index("ix_papers_normalized_title", "papers", ["normalized_title"], unique=False)
    op.create_table(
        "prompt_versions",
        sa.Column("prompt_version_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("template_sha256", sa.String(length=64), nullable=False),
        sa.Column("template_body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("prompt_version_id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("name", "version", name="uq_prompt_name_version"),
    )
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.String(length=32), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tag_id", name=op.f("pk_tags")),
        sa.UniqueConstraint("namespace", "normalized_name", name="uq_tag_ns_name"),
    )
    op.create_table(
        "techniques",
        sa.Column("technique_entity_id", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("problem_addressed", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("procedure_summary", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("conditions", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("reported_effect", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("cost_or_tradeoff", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("transferability_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("technique_entity_id", name=op.f("pk_techniques")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_techniques_normalized_name")),
    )
    op.create_table(
        "trace_events",
        sa.Column("event_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=255), nullable=False),
        sa.Column("module_id", sa.String(length=255), nullable=True),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("model_call_id", sa.String(length=32), nullable=True),
        sa.Column("level", sa.String(length=16), server_default=sa.text("'INFO'"), nullable=False),
        sa.Column("message", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_trace_events")),
    )
    op.create_index(
        "ix_trace_events_trace_time", "trace_events", ["trace_id", "occurred_at"], unique=False
    )
    op.create_table(
        "venue_registry",
        sa.Column("venue_registry_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("venue_id", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("peer_reviewed", sa.Boolean(), nullable=True),
        sa.Column("ranking_system", sa.String(length=255), nullable=True),
        sa.Column("ranking_value", sa.String(length=255), nullable=True),
        sa.Column("ranking_year", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("source_retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("venue_registry_id", name=op.f("pk_venue_registry")),
        sa.UniqueConstraint("venue_id", "ranking_system", "ranking_year", name="uq_venue_ranking"),
    )
    op.create_index(
        op.f("ix_venue_registry_venue_id"), "venue_registry", ["venue_id"], unique=False
    )
    op.create_table(
        "collection_papers",
        sa.Column("collection_id", sa.String(length=32), nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column(
            "priority_override_tier",
            sa.Enum(
                "T0_INDEX",
                "T1_SCAN",
                "T2_FULL",
                "T3_DEEP",
                name="resourcetier",
                native_enum=False,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("relevance_note", sa.Text(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.collection_id"],
            name=op.f("fk_collection_papers_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_collection_papers_paper_id_papers")
        ),
        sa.PrimaryKeyConstraint("collection_id", "paper_id", name=op.f("pk_collection_papers")),
    )
    op.create_table(
        "entity_tags",
        sa.Column("entity_id", sa.String(length=32), nullable=False),
        sa.Column("tag_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.entity_id"], name=op.f("fk_entity_tags_entity_id_entities")
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.tag_id"], name=op.f("fk_entity_tags_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint("entity_id", "tag_id", name=op.f("pk_entity_tags")),
    )
    op.create_table(
        "paper_versions",
        sa.Column("paper_version_id", sa.String(length=32), nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.Column("version_label", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=255), nullable=False),
        sa.Column("source_locator", sa.Text(), nullable=True),
        sa.Column("asset_id", sa.String(length=32), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("publication_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_preprint", sa.Boolean(), nullable=False),
        sa.Column("is_camera_ready", sa.Boolean(), nullable=False),
        sa.Column("is_supplementary", sa.Boolean(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.asset_id"], name=op.f("fk_paper_versions_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_paper_versions_paper_id_papers")
        ),
        sa.PrimaryKeyConstraint("paper_version_id", name=op.f("pk_paper_versions")),
        sa.UniqueConstraint("paper_id", "content_sha256", name="uq_version_content"),
        sa.UniqueConstraint("paper_id", "version_label", name="uq_version_label"),
    )
    op.create_index(
        op.f("ix_paper_versions_paper_id"), "paper_versions", ["paper_id"], unique=False
    )
    op.create_table(
        "tag_aliases",
        sa.Column("alias_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tag_id", sa.String(length=32), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("normalized_alias", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.tag_id"], name=op.f("fk_tag_aliases_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint("alias_id", name=op.f("pk_tag_aliases")),
        sa.UniqueConstraint("normalized_alias", name=op.f("uq_tag_aliases_normalized_alias")),
    )
    op.create_index(op.f("ix_tag_aliases_tag_id"), "tag_aliases", ["tag_id"], unique=False)
    op.create_table(
        "technique_papers",
        sa.Column("technique_entity_id", sa.String(length=255), nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_technique_papers_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["technique_entity_id"],
            ["techniques.technique_entity_id"],
            name=op.f("fk_technique_papers_technique_entity_id_techniques"),
        ),
        sa.PrimaryKeyConstraint(
            "technique_entity_id", "paper_id", name=op.f("pk_technique_papers")
        ),
    )
    op.create_table(
        "analysis_runs",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=True),
        sa.Column("paper_version_id", sa.String(length=32), nullable=True),
        sa.Column("collection_id", sa.String(length=32), nullable=True),
        sa.Column("agent_type", sa.String(length=255), nullable=False),
        sa.Column("pipeline_version", sa.String(length=255), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "WAITING",
                "RETRYING",
                "SUCCEEDED",
                "SUCCEEDED_WITH_WARNINGS",
                "BLOCKED",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="taskstate",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.collection_id"],
            name=op.f("fk_analysis_runs_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_analysis_runs_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.paper_version_id"],
            name=op.f("fk_analysis_runs_paper_version_id_paper_versions"),
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_analysis_runs")),
    )
    op.create_index(
        op.f("ix_analysis_runs_collection_id"), "analysis_runs", ["collection_id"], unique=False
    )
    op.create_index(op.f("ix_analysis_runs_paper_id"), "analysis_runs", ["paper_id"], unique=False)
    op.create_index(
        op.f("ix_analysis_runs_paper_version_id"),
        "analysis_runs",
        ["paper_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_analysis_runs_trace_id"), "analysis_runs", ["trace_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.Column("paper_version_id", sa.String(length=32), nullable=False),
        sa.Column(
            "requested_tier",
            sa.Enum(
                "T0_INDEX",
                "T1_SCAN",
                "T2_FULL",
                "T3_DEEP",
                name="resourcetier",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "T0_INDEX",
                "T1_SCAN",
                "T2_FULL",
                "T3_DEEP",
                name="resourcetier",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "WAITING",
                "RETRYING",
                "SUCCEEDED",
                "SUCCEEDED_WITH_WARNINGS",
                "BLOCKED",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="taskstate",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "current_stage",
            sa.Enum(
                "IMPORTED",
                "FINGERPRINTED",
                "METADATA_RESOLVED",
                "PDF_INSPECTED",
                "EXTRACTED",
                "STRUCTURED",
                "EVIDENCE_INDEXED",
                "TRIAGED",
                "ANALYZED",
                "VERIFIED",
                "SYNTHESIZED",
                "LINKED",
                "SEARCH_INDEXED",
                "CORPUS_READY",
                name="pipelinestage",
                native_enum=False,
                length=48,
            ),
            server_default=sa.text("'IMPORTED'"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_jobs_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.paper_version_id"],
            name=op.f("fk_jobs_paper_version_id_paper_versions"),
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_paper_id"), "jobs", ["paper_id"], unique=False)
    op.create_index("ix_jobs_state_priority", "jobs", ["state", "priority"], unique=False)
    op.create_index(op.f("ix_jobs_trace_id"), "jobs", ["trace_id"], unique=False)
    op.create_table(
        "sections",
        sa.Column("section_id", sa.String(length=255), nullable=False),
        sa.Column("paper_version_id", sa.String(length=32), nullable=False),
        sa.Column("parent_section_id", sa.String(length=255), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("original_heading", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "normalized_class",
            sa.Enum(
                "TITLE",
                "ABSTRACT",
                "INTRODUCTION",
                "RELATED_WORK",
                "BACKGROUND",
                "METHOD",
                "THEORY",
                "EXPERIMENT",
                "RESULT",
                "DISCUSSION",
                "LIMITATION",
                "CONCLUSION",
                "ACKNOWLEDGEMENT",
                "REFERENCES",
                "APPENDIX",
                "SUPPLEMENTARY",
                "OTHER",
                name="sectionclass",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.paper_version_id"],
            name=op.f("fk_sections_paper_version_id_paper_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_section_id"],
            ["sections.section_id"],
            name=op.f("fk_sections_parent_section_id_sections"),
        ),
        sa.PrimaryKeyConstraint("section_id", name=op.f("pk_sections")),
    )
    op.create_index(
        op.f("ix_sections_paper_version_id"), "sections", ["paper_version_id"], unique=False
    )
    op.create_index(
        "ix_sections_pver_ordinal", "sections", ["paper_version_id", "ordinal"], unique=False
    )
    op.create_table(
        "claims",
        sa.Column("claim_id", sa.String(length=32), nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.Column("paper_version_id", sa.String(length=32), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "FACT",
                "INFERENCE",
                "CRITIQUE",
                "EXTERNAL",
                name="claimtype",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("normalized_statement", sa.Text(), nullable=True),
        sa.Column(
            "support_state",
            sa.Enum(
                "UNVERIFIED",
                "SUPPORTED",
                "PARTIALLY_SUPPORTED",
                "DISPUTED",
                "UNSUPPORTED",
                "RETRACTED",
                "INSUFFICIENT_EVIDENCE",
                name="supportstate",
                native_enum=False,
                length=48,
            ),
            server_default=sa.text("'UNVERIFIED'"),
            nullable=False,
        ),
        sa.Column("analysis_confidence", sa.Float(), nullable=True),
        sa.Column("system_confidence", sa.Float(), nullable=True),
        sa.Column(
            "system_confidence_components", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_by_run_id", sa.String(length=32), nullable=False),
        sa.Column("pipeline_version", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("superseded_by_claim_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_run_id"],
            ["analysis_runs.run_id"],
            name=op.f("fk_claims_created_by_run_id_analysis_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_claims_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.paper_version_id"],
            name=op.f("fk_claims_paper_version_id_paper_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_claim_id"],
            ["claims.claim_id"],
            name=op.f("fk_claims_superseded_by_claim_id_claims"),
        ),
        sa.PrimaryKeyConstraint("claim_id", name=op.f("pk_claims")),
    )
    op.create_index("ix_claims_category", "claims", ["category"], unique=False)
    op.create_index(op.f("ix_claims_paper_id"), "claims", ["paper_id"], unique=False)
    op.create_index(
        op.f("ix_claims_paper_version_id"), "claims", ["paper_version_id"], unique=False
    )
    op.create_index("ix_claims_type_state", "claims", ["claim_type", "support_state"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("evidence_id", sa.String(length=32), nullable=False),
        sa.Column("paper_version_id", sa.String(length=32), nullable=False),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "PARAGRAPH",
                "HEADING",
                "CAPTION",
                "TABLE",
                "TABLE_CELL",
                "FIGURE",
                "FIGURE_REGION",
                "EQUATION",
                "REFERENCE",
                "FOOTNOTE",
                "METADATA",
                name="evidencetype",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("section_id", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("asset_id", sa.String(length=32), nullable=True),
        sa.Column(
            "source_method",
            sa.Enum(
                "PDF_NATIVE",
                "OCR",
                "MIXED_NATIVE_OCR",
                "IMPORTED_METADATA",
                name="sourcemethod",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column(
            "quality_state",
            sa.Enum(
                "GOOD",
                "DEGRADED",
                "POOR",
                "UNKNOWN",
                name="dataqualitystate",
                native_enum=False,
                length=48,
            ),
            server_default=sa.text("'UNKNOWN'"),
            nullable=False,
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("extraction_run_id", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("supersedes_evidence_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.asset_id"], name=op.f("fk_evidence_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["analysis_runs.run_id"],
            name=op.f("fk_evidence_extraction_run_id_analysis_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.paper_version_id"],
            name=op.f("fk_evidence_paper_version_id_paper_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_evidence_id"],
            ["evidence.evidence_id"],
            name=op.f("fk_evidence_supersedes_evidence_id_evidence"),
        ),
        sa.PrimaryKeyConstraint("evidence_id", name=op.f("pk_evidence")),
    )
    op.create_index(
        op.f("ix_evidence_paper_version_id"), "evidence", ["paper_version_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_section_id"), "evidence", ["section_id"], unique=False)
    op.create_table(
        "paper_tags",
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.Column("tag_id", sa.String(length=32), nullable=False),
        sa.Column("created_by_run_id", sa.String(length=32), nullable=True),
        sa.Column("is_candidate", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_run_id"],
            ["analysis_runs.run_id"],
            name=op.f("fk_paper_tags_created_by_run_id_analysis_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_paper_tags_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.tag_id"], name=op.f("fk_paper_tags_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint("paper_id", "tag_id", name=op.f("pk_paper_tags")),
    )
    op.create_table(
        "quality_assessments",
        sa.Column("quality_assessment_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.Column(
            "dimension",
            sa.Enum(
                "METHODOLOGICAL_RIGOR",
                "EXPERIMENTAL_RIGOR",
                "BASELINE_FAIRNESS",
                "ABLATION_COMPLETENESS",
                "STATISTICAL_RELIABILITY",
                "REPRODUCIBILITY",
                "DATA_QUALITY",
                "CLAIM_EVIDENCE_ALIGNMENT",
                "NOVELTY",
                "ENGINEERING_USEFULNESS",
                "TRANSFERABILITY",
                "CLARITY",
                name="qualitydimension",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("assessment", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("counter_evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("system_confidence", sa.Float(), nullable=True),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_quality_assessments_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.run_id"],
            name=op.f("fk_quality_assessments_run_id_analysis_runs"),
        ),
        sa.PrimaryKeyConstraint("quality_assessment_id", name=op.f("pk_quality_assessments")),
        sa.UniqueConstraint("paper_id", "dimension", "run_id", name="uq_quality_paper_dim_run"),
    )
    op.create_index(
        op.f("ix_quality_assessments_paper_id"), "quality_assessments", ["paper_id"], unique=False
    )
    op.create_table(
        "relations",
        sa.Column("relation_id", sa.String(length=32), nullable=False),
        sa.Column("source_entity_id", sa.String(length=32), nullable=False),
        sa.Column("relation_type", sa.String(length=255), nullable=False),
        sa.Column("target_entity_id", sa.String(length=32), nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=True),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_by_run_id", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_run_id"],
            ["analysis_runs.run_id"],
            name=op.f("fk_relations_created_by_run_id_analysis_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_relations_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_relations_source_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_relations_target_entity_id_entities"),
        ),
        sa.PrimaryKeyConstraint("relation_id", name=op.f("pk_relations")),
    )
    op.create_index(op.f("ix_relations_paper_id"), "relations", ["paper_id"], unique=False)
    op.create_index(
        "ix_relations_source_type", "relations", ["source_entity_id", "relation_type"], unique=False
    )
    op.create_index(
        "ix_relations_target_type", "relations", ["target_entity_id", "relation_type"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("task_type", sa.String(length=255), nullable=False),
        sa.Column("module_id", sa.String(length=255), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "WAITING",
                "RETRYING",
                "SUCCEEDED",
                "SUCCEEDED_WITH_WARNINGS",
                "BLOCKED",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="taskstate",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "quality_state",
            sa.Enum(
                "GOOD",
                "DEGRADED",
                "POOR",
                "UNKNOWN",
                name="dataqualitystate",
                native_enum=False,
                length=48,
            ),
            server_default=sa.text("'UNKNOWN'"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("input_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=16), nullable=True),
        sa.Column("error_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], name=op.f("fk_tasks_job_id_jobs")),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_tasks_idempotency_key")),
    )
    op.create_index(op.f("ix_tasks_job_id"), "tasks", ["job_id"], unique=False)
    op.create_index("ix_tasks_state_priority", "tasks", ["state", "priority"], unique=False)
    op.create_index(op.f("ix_tasks_trace_id"), "tasks", ["trace_id"], unique=False)
    op.create_index("ix_tasks_type_state", "tasks", ["task_type", "state"], unique=False)
    op.create_table(
        "triage_results",
        sa.Column("triage_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.String(length=32), nullable=False),
        sa.Column(
            "recommended_tier",
            sa.Enum(
                "T0_INDEX",
                "T1_SCAN",
                "T2_FULL",
                "T3_DEEP",
                name="resourcetier",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "effective_tier",
            sa.Enum(
                "T0_INDEX",
                "T1_SCAN",
                "T2_FULL",
                "T3_DEEP",
                name="resourcetier",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("manual_override", sa.Boolean(), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by_run_id", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_run_id"],
            ["analysis_runs.run_id"],
            name=op.f("fk_triage_results_created_by_run_id_analysis_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.paper_id"], name=op.f("fk_triage_results_paper_id_papers")
        ),
        sa.PrimaryKeyConstraint("triage_id", name=op.f("pk_triage_results")),
    )
    op.create_index(
        op.f("ix_triage_results_paper_id"), "triage_results", ["paper_id"], unique=False
    )
    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.String(length=32), nullable=False),
        sa.Column("evidence_id", sa.String(length=32), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "SUPPORT",
                "COUNTER_EVIDENCE",
                "CONTEXT",
                name="evidencerole",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.claim_id"], name=op.f("fk_claim_evidence_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.evidence_id"],
            name=op.f("fk_claim_evidence_evidence_id_evidence"),
        ),
        sa.PrimaryKeyConstraint("claim_id", "evidence_id", name=op.f("pk_claim_evidence")),
    )
    op.create_table(
        "external_provenances",
        sa.Column("provenance_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("claim_id", sa.String(length=32), nullable=False),
        sa.Column("source_provider", sa.String(length=255), nullable=False),
        sa.Column("source_identifier", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("citation_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.claim_id"], name=op.f("fk_external_provenances_claim_id_claims")
        ),
        sa.PrimaryKeyConstraint("provenance_id", name=op.f("pk_external_provenances")),
    )
    op.create_index(
        op.f("ix_external_provenances_claim_id"), "external_provenances", ["claim_id"], unique=False
    )
    op.create_table(
        "model_calls",
        sa.Column("model_call_id", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("prompt_version_id", sa.String(length=32), nullable=False),
        sa.Column("request_manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_object_hash", sa.String(length=64), nullable=True),
        sa.Column("response_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "transport_status",
            sa.Enum(
                "OK",
                "TIMEOUT",
                "RATE_LIMITED",
                "HTTP_CLIENT_ERROR",
                "HTTP_SERVER_ERROR",
                "CONNECTION_ERROR",
                "UNKNOWN",
                name="transportstatus",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "schema_status",
            sa.Enum(
                "NOT_RUN",
                "PASSED",
                "PASSED_AFTER_REPAIR",
                "JSON_INVALID",
                "SCHEMA_INVALID",
                "SEMANTIC_INVALID",
                "EVIDENCE_INVALID",
                name="schemastatus",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("retry_number", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.prompt_version_id"],
            name=op.f("fk_model_calls_prompt_version_id_prompt_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["analysis_runs.run_id"], name=op.f("fk_model_calls_run_id_analysis_runs")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.task_id"], name=op.f("fk_model_calls_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("model_call_id", name=op.f("pk_model_calls")),
    )
    op.create_index(op.f("ix_model_calls_run_id"), "model_calls", ["run_id"], unique=False)
    op.create_index(op.f("ix_model_calls_task_id"), "model_calls", ["task_id"], unique=False)
    op.create_index(op.f("ix_model_calls_trace_id"), "model_calls", ["trace_id"], unique=False)
    op.create_table(
        "verifications",
        sa.Column("verification_id", sa.String(length=32), nullable=False),
        sa.Column("claim_id", sa.String(length=32), nullable=False),
        sa.Column(
            "verifier_type",
            sa.Enum(
                "CITATION",
                "EVIDENCE_EXISTENCE",
                "NUMERIC",
                "CLAIM_SCOPE",
                "CONTRADICTION",
                "INDEPENDENT_CONSENSUS",
                "FALSIFICATION",
                "OCR_SENSITIVITY",
                "EXTERNAL_NOVELTY",
                name="verifiertype",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "PASS",
                "WARN",
                "FAIL",
                "INCONCLUSIVE",
                name="verifierverdict",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("reason_summary", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by_run_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.claim_id"], name=op.f("fk_verifications_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_run_id"],
            ["analysis_runs.run_id"],
            name=op.f("fk_verifications_created_by_run_id_analysis_runs"),
        ),
        sa.PrimaryKeyConstraint("verification_id", name=op.f("pk_verifications")),
    )
    op.create_index(op.f("ix_verifications_claim_id"), "verifications", ["claim_id"], unique=False)
    op.create_index(
        "ix_verifications_type_verdict", "verifications", ["verifier_type", "verdict"], unique=False
    )
    # ### end Alembic commands ###

    # Evidence immutability enforcement (spec doc 03 §1.4): no UPDATE of
    # canonical evidence content, no DELETE. Corrections create a NEW evidence
    # row with supersedes_evidence_id linkage. Only structure re-linking
    # (section_id) and quality re-assessment (quality_state) may change.
    # TRUNCATE (test-fixture cleanup) intentionally bypasses row triggers.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION evidence_immutable_guard() RETURNS trigger AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'EVIDENCE_IMMUTABLE: evidence % cannot be deleted; corrections supersede via new rows', OLD.evidence_id
              USING ERRCODE = 'P0001';
          END IF;
          IF (NEW.evidence_type IS DISTINCT FROM OLD.evidence_type
              OR NEW.page_start IS DISTINCT FROM OLD.page_start
              OR NEW.page_end IS DISTINCT FROM OLD.page_end
              OR NEW.bbox IS DISTINCT FROM OLD.bbox
              OR NEW.text IS DISTINCT FROM OLD.text
              OR NEW.asset_id IS DISTINCT FROM OLD.asset_id
              OR NEW.source_method IS DISTINCT FROM OLD.source_method
              OR NEW.ocr_confidence IS DISTINCT FROM OLD.ocr_confidence
              OR NEW.content_sha256 IS DISTINCT FROM OLD.content_sha256
              OR NEW.paper_version_id IS DISTINCT FROM OLD.paper_version_id
              OR NEW.extraction_run_id IS DISTINCT FROM OLD.extraction_run_id
              OR NEW.created_at IS DISTINCT FROM OLD.created_at
              OR NEW.supersedes_evidence_id IS DISTINCT FROM OLD.supersedes_evidence_id) THEN
            RAISE EXCEPTION 'EVIDENCE_IMMUTABLE: canonical evidence content % cannot be updated; create a superseding evidence row', NEW.evidence_id
              USING ERRCODE = 'P0001';
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER evidence_immutable_guard
        BEFORE UPDATE OR DELETE ON evidence
        FOR EACH ROW EXECUTE FUNCTION evidence_immutable_guard();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS evidence_immutable_guard ON evidence")
    op.execute("DROP FUNCTION IF EXISTS evidence_immutable_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verifications_type_verdict", table_name="verifications")
    op.drop_index(op.f("ix_verifications_claim_id"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_index(op.f("ix_model_calls_trace_id"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_task_id"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_run_id"), table_name="model_calls")
    op.drop_table("model_calls")
    op.drop_index(op.f("ix_external_provenances_claim_id"), table_name="external_provenances")
    op.drop_table("external_provenances")
    op.drop_table("claim_evidence")
    op.drop_index(op.f("ix_triage_results_paper_id"), table_name="triage_results")
    op.drop_table("triage_results")
    op.drop_index("ix_tasks_type_state", table_name="tasks")
    op.drop_index(op.f("ix_tasks_trace_id"), table_name="tasks")
    op.drop_index("ix_tasks_state_priority", table_name="tasks")
    op.drop_index(op.f("ix_tasks_job_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_relations_target_type", table_name="relations")
    op.drop_index("ix_relations_source_type", table_name="relations")
    op.drop_index(op.f("ix_relations_paper_id"), table_name="relations")
    op.drop_table("relations")
    op.drop_index(op.f("ix_quality_assessments_paper_id"), table_name="quality_assessments")
    op.drop_table("quality_assessments")
    op.drop_table("paper_tags")
    op.drop_index(op.f("ix_evidence_section_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_paper_version_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index("ix_claims_type_state", table_name="claims")
    op.drop_index(op.f("ix_claims_paper_version_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_paper_id"), table_name="claims")
    op.drop_index("ix_claims_category", table_name="claims")
    op.drop_table("claims")
    op.drop_index("ix_sections_pver_ordinal", table_name="sections")
    op.drop_index(op.f("ix_sections_paper_version_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_jobs_trace_id"), table_name="jobs")
    op.drop_index("ix_jobs_state_priority", table_name="jobs")
    op.drop_index(op.f("ix_jobs_paper_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_analysis_runs_trace_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_paper_version_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_paper_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_collection_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_table("technique_papers")
    op.drop_index(op.f("ix_tag_aliases_tag_id"), table_name="tag_aliases")
    op.drop_table("tag_aliases")
    op.drop_index(op.f("ix_paper_versions_paper_id"), table_name="paper_versions")
    op.drop_table("paper_versions")
    op.drop_table("entity_tags")
    op.drop_table("collection_papers")
    op.drop_index(op.f("ix_venue_registry_venue_id"), table_name="venue_registry")
    op.drop_table("venue_registry")
    op.drop_index("ix_trace_events_trace_time", table_name="trace_events")
    op.drop_table("trace_events")
    op.drop_table("techniques")
    op.drop_table("tags")
    op.drop_table("prompt_versions")
    op.drop_index("ix_papers_normalized_title", table_name="papers")
    op.drop_table("papers")
    op.drop_table("entities")
    op.drop_table("collections")
    op.drop_table("assets")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
